/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzx_phone_utils_NativeUtils */

#ifndef _Included_com_zzx_phone_utils_NativeUtils
#define _Included_com_zzx_phone_utils_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzx_phone_utils_NativeUtils
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzx_phone_utils_NativeUtils_getNativeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
